//
//  OpenSeaTests.swift
//  OpenSeaTests
//
//  Created by Kedia on 2023/1/16.
//

import XCTest
@testable import OpenSea

final class OpenSeaTests: XCTestCase {

    override func setUpWithError() throws {
        // Put setup code here. This method is called before the invocation of each test method in the class.
    }

    override func tearDownWithError() throws {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }

    func testAssetsList() {
        let data = assetsMockString.data(using: .utf8)!
        let container = try! JSONDecoder().decode(KDAssetsContainer.self, from: data)
        XCTAssertEqual(container.assets!.count, 20)
        let asset = container.assets!.first!
        XCTAssertEqual(asset.id, 160446791)
        XCTAssertEqual(asset.imageURLString, "https://i.seadn.io/gae/0MltSFh7igKq64MpKUyfdXTEcDpZ1AB7BrbWsEXYDmavuk55drBAyjh1BKueBK97BWZuTSvUCm8_O_hg835Ons4YBmU-Slcwh66uZA?w=500&auto=format")
        XCTAssertEqual(asset.thumbnailURLString, "https://i.seadn.io/gae/0MltSFh7igKq64MpKUyfdXTEcDpZ1AB7BrbWsEXYDmavuk55drBAyjh1BKueBK97BWZuTSvUCm8_O_hg835Ons4YBmU-Slcwh66uZA?w=500&auto=format")
        XCTAssertEqual(asset.permalink, "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/4")
        XCTAssertEqual(asset.name, "Cart")
        XCTAssertEqual(asset.collectionName, "BloctoAssignment V2")
        XCTAssertEqual(asset.description, "Blocto assignment second collection")
    }

    let assetsMockString = #"""
{
  "assets": [
    {
      "id": 160446791,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/0MltSFh7igKq64MpKUyfdXTEcDpZ1AB7BrbWsEXYDmavuk55drBAyjh1BKueBK97BWZuTSvUCm8_O_hg835Ons4YBmU-Slcwh66uZA?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/0MltSFh7igKq64MpKUyfdXTEcDpZ1AB7BrbWsEXYDmavuk55drBAyjh1BKueBK97BWZuTSvUCm8_O_hg835Ons4YBmU-Slcwh66uZA?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/0MltSFh7igKq64MpKUyfdXTEcDpZ1AB7BrbWsEXYDmavuk55drBAyjh1BKueBK97BWZuTSvUCm8_O_hg835Ons4YBmU-Slcwh66uZA?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Cart.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Cart",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/4",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/4",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "4"
    },
    {
      "id": 160446787,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/cpGrf9zxLbi4zLVC-4bA0jTSx0oZdWCvFLW375KDowJVj0pxiqRHGcSEqR0JymR9PYxHjztlII9CGz7xQVfH2oBNZhTiFPAeZcWHGR0?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/cpGrf9zxLbi4zLVC-4bA0jTSx0oZdWCvFLW375KDowJVj0pxiqRHGcSEqR0JymR9PYxHjztlII9CGz7xQVfH2oBNZhTiFPAeZcWHGR0?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/cpGrf9zxLbi4zLVC-4bA0jTSx0oZdWCvFLW375KDowJVj0pxiqRHGcSEqR0JymR9PYxHjztlII9CGz7xQVfH2oBNZhTiFPAeZcWHGR0?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Smaile.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Smaile",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/11",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/11",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "11"
    },
    {
      "id": 160446786,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/FJoy6BJ9WpWkZ5NdESD0T53PjMRcJoi6luIHoU1m_mkDGbszcVQ2J1M_7gzKkFmJxXGUPQ0tVrgv8JV_tGw4Ta8XMsNiXyir66vBDw?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/FJoy6BJ9WpWkZ5NdESD0T53PjMRcJoi6luIHoU1m_mkDGbszcVQ2J1M_7gzKkFmJxXGUPQ0tVrgv8JV_tGw4Ta8XMsNiXyir66vBDw?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/FJoy6BJ9WpWkZ5NdESD0T53PjMRcJoi6luIHoU1m_mkDGbszcVQ2J1M_7gzKkFmJxXGUPQ0tVrgv8JV_tGw4Ta8XMsNiXyir66vBDw?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Support.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Support",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/12",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/12",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "12"
    },
    {
      "id": 160446785,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/MiQOL92rfcHkafwgGAN8Ak9aQGOTlGVkKhPOPM4Ln-encjnpjHviXkOdJ97dFKNdqTQv_ENimd3oM7BLrJDU24KOvGtZ4EdwhjKN?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/MiQOL92rfcHkafwgGAN8Ak9aQGOTlGVkKhPOPM4Ln-encjnpjHviXkOdJ97dFKNdqTQv_ENimd3oM7BLrJDU24KOvGtZ4EdwhjKN?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/MiQOL92rfcHkafwgGAN8Ak9aQGOTlGVkKhPOPM4Ln-encjnpjHviXkOdJ97dFKNdqTQv_ENimd3oM7BLrJDU24KOvGtZ4EdwhjKN?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Logout.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Logout",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/8",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/8",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "8"
    },
    {
      "id": 160446784,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/pfF_XRWze_lAoUVar6NBaJLMlgsefZHhOSllmWIhQYNVSFxCEMS_lkK0RQysrS6u_zjfeuff0Pfdlx4G3cG13S4aTRh5U_hz6V7BFw?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/pfF_XRWze_lAoUVar6NBaJLMlgsefZHhOSllmWIhQYNVSFxCEMS_lkK0RQysrS6u_zjfeuff0Pfdlx4G3cG13S4aTRh5U_hz6V7BFw?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/pfF_XRWze_lAoUVar6NBaJLMlgsefZHhOSllmWIhQYNVSFxCEMS_lkK0RQysrS6u_zjfeuff0Pfdlx4G3cG13S4aTRh5U_hz6V7BFw?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/File.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "File",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/6",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/6",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "6"
    },
    {
      "id": 160446783,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/yXkkMjUGtBoVJr9jFa2kDNHyijHQSmUFvLCHSrmqLLz2EFl7QsBV6b50eYydIQgULGPdrW9cAsFVxjakyqNBQqQlaiXz3hkkx7nJxA?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/yXkkMjUGtBoVJr9jFa2kDNHyijHQSmUFvLCHSrmqLLz2EFl7QsBV6b50eYydIQgULGPdrW9cAsFVxjakyqNBQqQlaiXz3hkkx7nJxA?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/yXkkMjUGtBoVJr9jFa2kDNHyijHQSmUFvLCHSrmqLLz2EFl7QsBV6b50eYydIQgULGPdrW9cAsFVxjakyqNBQqQlaiXz3hkkx7nJxA?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/History.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "History",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/7",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/7",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "7"
    },
    {
      "id": 160446782,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/V3jH-Vg3EEYRym_marbjRUWl-KyKgFxWI27eMB15NxGOopmw1TPpzDjarkQs2G-vucSspAHzWonHvnH0uWh8Fxd7xq9Tw-gmYPg-wKs?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/V3jH-Vg3EEYRym_marbjRUWl-KyKgFxWI27eMB15NxGOopmw1TPpzDjarkQs2G-vucSspAHzWonHvnH0uWh8Fxd7xq9Tw-gmYPg-wKs?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/V3jH-Vg3EEYRym_marbjRUWl-KyKgFxWI27eMB15NxGOopmw1TPpzDjarkQs2G-vucSspAHzWonHvnH0uWh8Fxd7xq9Tw-gmYPg-wKs?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Calendar.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Calendar",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/3",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/3",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "3"
    },
    {
      "id": 160446781,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/KhPXLqve5eFV_fmM-oc4kNc_FXH0b_yJUvE2Jc6FhFnNSwbMmksmuMnRwLEBtiHhAIkp7RjgCS6udEqooueio8lR23eZWBdjaK3o9Fg?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/KhPXLqve5eFV_fmM-oc4kNc_FXH0b_yJUvE2Jc6FhFnNSwbMmksmuMnRwLEBtiHhAIkp7RjgCS6udEqooueio8lR23eZWBdjaK3o9Fg?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/KhPXLqve5eFV_fmM-oc4kNc_FXH0b_yJUvE2Jc6FhFnNSwbMmksmuMnRwLEBtiHhAIkp7RjgCS6udEqooueio8lR23eZWBdjaK3o9Fg?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Revoke.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Revoke",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/9",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/9",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "9"
    },
    {
      "id": 160446780,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/qfLAiT_Qrl_2CQODPRLJNxQGmW3gkmjyuprfB6W8Q2TKZ_EAUTupkfnSO_TzRuc0Cs0GW1d0OvidpCGv8j80qq_rhT7kXu-iSNzHmHE?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/qfLAiT_Qrl_2CQODPRLJNxQGmW3gkmjyuprfB6W8Q2TKZ_EAUTupkfnSO_TzRuc0Cs0GW1d0OvidpCGv8j80qq_rhT7kXu-iSNzHmHE?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/qfLAiT_Qrl_2CQODPRLJNxQGmW3gkmjyuprfB6W8Q2TKZ_EAUTupkfnSO_TzRuc0Cs0GW1d0OvidpCGv8j80qq_rhT7kXu-iSNzHmHE?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Addressbook.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Addressbook",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/1",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/1",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "1"
    },
    {
      "id": 160446779,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/p-7sEWxn27q9UFPUYyTJS230ixpygp_H6_eJk2g-SbuEdyZSfQjd4c9a-bJUriUP7Yuq6KFMwK6SaGEMsKMwedS2QE5swj8oEuI_?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/p-7sEWxn27q9UFPUYyTJS230ixpygp_H6_eJk2g-SbuEdyZSfQjd4c9a-bJUriUP7Yuq6KFMwK6SaGEMsKMwedS2QE5swj8oEuI_?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/p-7sEWxn27q9UFPUYyTJS230ixpygp_H6_eJk2g-SbuEdyZSfQjd4c9a-bJUriUP7Yuq6KFMwK6SaGEMsKMwedS2QE5swj8oEuI_?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Sell.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Sell",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/10",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/10",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "10"
    },
    {
      "id": 160446778,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/pi3_nQ0QJUFDpUFwU9wyB8zKAo0U_t4ngs9_XGeVeBwwdxTejsJwt5JUDipGcB8mCCpXzvAbbAL48skcM4jerqfny_p1rCbWuuf_MQ?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/pi3_nQ0QJUFDpUFwU9wyB8zKAo0U_t4ngs9_XGeVeBwwdxTejsJwt5JUDipGcB8mCCpXzvAbbAL48skcM4jerqfny_p1rCbWuuf_MQ?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/pi3_nQ0QJUFDpUFwU9wyB8zKAo0U_t4ngs9_XGeVeBwwdxTejsJwt5JUDipGcB8mCCpXzvAbbAL48skcM4jerqfny_p1rCbWuuf_MQ?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Accelerate.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Accelerate",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/0",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/0",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "0"
    },
    {
      "id": 160446777,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/4Ie5TSOo4UQRcA4xNvdE5YNTgEvDCGGkgVjz90lHBve2OvsMVbt7r6vCkYa5G1PPJTAeJqQcYQSXGJxJ8ODN-RBPQIIh7ehCAu4_kQ?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/4Ie5TSOo4UQRcA4xNvdE5YNTgEvDCGGkgVjz90lHBve2OvsMVbt7r6vCkYa5G1PPJTAeJqQcYQSXGJxJ8ODN-RBPQIIh7ehCAu4_kQ?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/4Ie5TSOo4UQRcA4xNvdE5YNTgEvDCGGkgVjz90lHBve2OvsMVbt7r6vCkYa5G1PPJTAeJqQcYQSXGJxJ8ODN-RBPQIIh7ehCAu4_kQ?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Announcement.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Announcement",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/2",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/2",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "2"
    },
    {
      "id": 160446776,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/dOoFB6PVDsv8xqmIbiyz-udbaGB_Lfk8OhJT07A1wLaxka_lX46XsqnnHTA6fVyuiAI1RJ66gqZHFe0Uv7CZdln1bJkSIeYKseUpXA?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/dOoFB6PVDsv8xqmIbiyz-udbaGB_Lfk8OhJT07A1wLaxka_lX46XsqnnHTA6fVyuiAI1RJ66gqZHFe0Uv7CZdln1bJkSIeYKseUpXA?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/dOoFB6PVDsv8xqmIbiyz-udbaGB_Lfk8OhJT07A1wLaxka_lX46XsqnnHTA6fVyuiAI1RJ66gqZHFe0Uv7CZdln1bJkSIeYKseUpXA?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Tool.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Tool",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/13",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/13",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "13"
    },
    {
      "id": 160446775,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/_-FnthkYZuLqhaBsZxp0xqhGDPfR5nkwNmQnUq_nIoob1ox33qYHdeP7guh5byPEDd724_i8HbS1UvdyXWEb71Z-bSRA6ziTwkrAdw?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/_-FnthkYZuLqhaBsZxp0xqhGDPfR5nkwNmQnUq_nIoob1ox33qYHdeP7guh5byPEDd724_i8HbS1UvdyXWEb71Z-bSRA6ziTwkrAdw?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/_-FnthkYZuLqhaBsZxp0xqhGDPfR5nkwNmQnUq_nIoob1ox33qYHdeP7guh5byPEDd724_i8HbS1UvdyXWEb71Z-bSRA6ziTwkrAdw?w=500&auto=format",
      "image_original_url": "ipfs://QmanU4QcTro4VMzJKvD3UtnKdaVusnpfmy2NBW7NNvoDAL/Docs.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Docs",
      "description": "Blocto assignment second collection",
      "external_link": null,
      "asset_contract": {
        "address": "0xc852e1a0be505e2cb925698ad1934424d11a3468",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T10:20:27.912826",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xc852e1a0be505e2cb925698ad1934424d11a3468/5",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T10:22:07.458477+00:00",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment V2",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment-v2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmWK4nupu7h2JN36eGJyhoueSxCJrvmkpmQCuogEJELaFH/5",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "5"
    },
    {
      "id": 160431740,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/ayvUbxBsw30iHMZnyysqJBoqUqCh9wWdTss0xVZx1Blfg9OFRCfIR7LEPnGoHsASSh-TWhQf9liAx7r_q7efdlcCqaLfKdqRQusH?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/ayvUbxBsw30iHMZnyysqJBoqUqCh9wWdTss0xVZx1Blfg9OFRCfIR7LEPnGoHsASSh-TWhQf9liAx7r_q7efdlcCqaLfKdqRQusH?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/ayvUbxBsw30iHMZnyysqJBoqUqCh9wWdTss0xVZx1Blfg9OFRCfIR7LEPnGoHsASSh-TWhQf9liAx7r_q7efdlcCqaLfKdqRQusH?w=500&auto=format",
      "image_original_url": "ipfs://QmZMB6Lkbk2mUpq4zqPxn8aJqQ8C9zMeMwRw8cjA9EXWsm/Loading.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Loading",
      "description": "Blocto assignment",
      "external_link": null,
      "asset_contract": {
        "address": "0xf37a02f497e21be9f4dd9a34c01568ac21578d1a",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T09:10:03.638607",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "An assignment to test several types of images of NFTs.",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xf37a02f497e21be9f4dd9a34c01568ac21578d1a/16",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T09:12:39.255914+00:00",
        "default_to_fiat": false,
        "description": "An assignment to test several types of images of NFTs.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmZHvscH2h5dXFHHvVCedreFDBEfFDWAQxsMjJTBiiKuZi/16",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "16"
    },
    {
      "id": 160431739,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/wcMDU5qxGLxL704lBz69BaBBHv70DGIypIMN3ISwRteiU8uidoMYaCq3RPbDT5hE7JOL0YvF8txRoJrH2ssPyUZQYUMI8c6NoV9EQw?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/wcMDU5qxGLxL704lBz69BaBBHv70DGIypIMN3ISwRteiU8uidoMYaCq3RPbDT5hE7JOL0YvF8txRoJrH2ssPyUZQYUMI8c6NoV9EQw?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/wcMDU5qxGLxL704lBz69BaBBHv70DGIypIMN3ISwRteiU8uidoMYaCq3RPbDT5hE7JOL0YvF8txRoJrH2ssPyUZQYUMI8c6NoV9EQw?w=500&auto=format",
      "image_original_url": "ipfs://QmZMB6Lkbk2mUpq4zqPxn8aJqQ8C9zMeMwRw8cjA9EXWsm/blt.gif",
      "animation_url": null,
      "animation_original_url": null,
      "name": "blt",
      "description": "Blocto assignment",
      "external_link": null,
      "asset_contract": {
        "address": "0xf37a02f497e21be9f4dd9a34c01568ac21578d1a",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T09:10:03.638607",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "An assignment to test several types of images of NFTs.",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xf37a02f497e21be9f4dd9a34c01568ac21578d1a/27",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T09:12:39.255914+00:00",
        "default_to_fiat": false,
        "description": "An assignment to test several types of images of NFTs.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmZHvscH2h5dXFHHvVCedreFDBEfFDWAQxsMjJTBiiKuZi/27",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "27"
    },
    {
      "id": 160431738,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/hA0o_VlgAY6NOig9vxGzL1bmDoSm-3Qu_qdku0kyR_Q3Mqgbj6nTecFnX8mC31aK8vWWLw2-3l4TXOKx7pclXG_SKyVG8Eyk2nZ0Tg?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/hA0o_VlgAY6NOig9vxGzL1bmDoSm-3Qu_qdku0kyR_Q3Mqgbj6nTecFnX8mC31aK8vWWLw2-3l4TXOKx7pclXG_SKyVG8Eyk2nZ0Tg?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/hA0o_VlgAY6NOig9vxGzL1bmDoSm-3Qu_qdku0kyR_Q3Mqgbj6nTecFnX8mC31aK8vWWLw2-3l4TXOKx7pclXG_SKyVG8Eyk2nZ0Tg?w=500&auto=format",
      "image_original_url": "ipfs://QmZMB6Lkbk2mUpq4zqPxn8aJqQ8C9zMeMwRw8cjA9EXWsm/Twitter.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Twitter",
      "description": "Blocto assignment",
      "external_link": null,
      "asset_contract": {
        "address": "0xf37a02f497e21be9f4dd9a34c01568ac21578d1a",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T09:10:03.638607",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "An assignment to test several types of images of NFTs.",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xf37a02f497e21be9f4dd9a34c01568ac21578d1a/24",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T09:12:39.255914+00:00",
        "default_to_fiat": false,
        "description": "An assignment to test several types of images of NFTs.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmZHvscH2h5dXFHHvVCedreFDBEfFDWAQxsMjJTBiiKuZi/24",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "24"
    },
    {
      "id": 160431737,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/nIUxPEKnWVgwiAZzg0Cj4BJHHCRNUdKDNkUtA3kZmET2f1KiV9feTYrXBZ9icsWUL-jsp6IiFi7C92kFz3ok-StaR87uJQXv9yeBGA?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/nIUxPEKnWVgwiAZzg0Cj4BJHHCRNUdKDNkUtA3kZmET2f1KiV9feTYrXBZ9icsWUL-jsp6IiFi7C92kFz3ok-StaR87uJQXv9yeBGA?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/nIUxPEKnWVgwiAZzg0Cj4BJHHCRNUdKDNkUtA3kZmET2f1KiV9feTYrXBZ9icsWUL-jsp6IiFi7C92kFz3ok-StaR87uJQXv9yeBGA?w=500&auto=format",
      "image_original_url": "ipfs://QmZMB6Lkbk2mUpq4zqPxn8aJqQ8C9zMeMwRw8cjA9EXWsm/medium.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "medium",
      "description": "Blocto assignment",
      "external_link": null,
      "asset_contract": {
        "address": "0xf37a02f497e21be9f4dd9a34c01568ac21578d1a",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T09:10:03.638607",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "An assignment to test several types of images of NFTs.",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xf37a02f497e21be9f4dd9a34c01568ac21578d1a/28",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T09:12:39.255914+00:00",
        "default_to_fiat": false,
        "description": "An assignment to test several types of images of NFTs.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmZHvscH2h5dXFHHvVCedreFDBEfFDWAQxsMjJTBiiKuZi/28",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "28"
    },
    {
      "id": 160431736,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/RdOJMsTOgxYoP3hJThePr2dmj5yTXZcnm_6SRj0_ET5YAyCLIo-kB00G3sJcy7gop23RHttKiEOhQ7cLh-b9HVT-V-UmXx_2OVtWYw?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/RdOJMsTOgxYoP3hJThePr2dmj5yTXZcnm_6SRj0_ET5YAyCLIo-kB00G3sJcy7gop23RHttKiEOhQ7cLh-b9HVT-V-UmXx_2OVtWYw?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/RdOJMsTOgxYoP3hJThePr2dmj5yTXZcnm_6SRj0_ET5YAyCLIo-kB00G3sJcy7gop23RHttKiEOhQ7cLh-b9HVT-V-UmXx_2OVtWYw?w=500&auto=format",
      "image_original_url": "ipfs://QmZMB6Lkbk2mUpq4zqPxn8aJqQ8C9zMeMwRw8cjA9EXWsm/Treasure.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Treasure",
      "description": "Blocto assignment",
      "external_link": null,
      "asset_contract": {
        "address": "0xf37a02f497e21be9f4dd9a34c01568ac21578d1a",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T09:10:03.638607",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "An assignment to test several types of images of NFTs.",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xf37a02f497e21be9f4dd9a34c01568ac21578d1a/23",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T09:12:39.255914+00:00",
        "default_to_fiat": false,
        "description": "An assignment to test several types of images of NFTs.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmZHvscH2h5dXFHHvVCedreFDBEfFDWAQxsMjJTBiiKuZi/23",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "23"
    },
    {
      "id": 160431735,
      "num_sales": 0,
      "background_color": null,
      "image_url": "https://i.seadn.io/gae/h54yDBUCLtmcok3o6j4QoKF-vc3hfQfDe8hdyADiJdD4xsWzsxIpFHIXjx7NlKcUY7k2ElIOXZ67FBbIiexXFPW100RRByKm006Z?w=500&auto=format",
      "image_preview_url": "https://i.seadn.io/gae/h54yDBUCLtmcok3o6j4QoKF-vc3hfQfDe8hdyADiJdD4xsWzsxIpFHIXjx7NlKcUY7k2ElIOXZ67FBbIiexXFPW100RRByKm006Z?w=500&auto=format",
      "image_thumbnail_url": "https://i.seadn.io/gae/h54yDBUCLtmcok3o6j4QoKF-vc3hfQfDe8hdyADiJdD4xsWzsxIpFHIXjx7NlKcUY7k2ElIOXZ67FBbIiexXFPW100RRByKm006Z?w=500&auto=format",
      "image_original_url": "ipfs://QmZMB6Lkbk2mUpq4zqPxn8aJqQ8C9zMeMwRw8cjA9EXWsm/Sent.png",
      "animation_url": null,
      "animation_original_url": null,
      "name": "Sent",
      "description": "Blocto assignment",
      "external_link": null,
      "asset_contract": {
        "address": "0xf37a02f497e21be9f4dd9a34c01568ac21578d1a",
        "asset_contract_type": "non-fungible",
        "created_date": "2022-12-07T09:10:03.638607",
        "name": "BloctoAssignment",
        "nft_version": "3.0",
        "opensea_version": null,
        "owner": 16064713,
        "schema_name": "ERC721",
        "symbol": "ASSIGNMENT",
        "total_supply": "0",
        "description": "An assignment to test several types of images of NFTs.",
        "external_link": "https://portto.com/",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "default_to_fiat": false,
        "dev_buyer_fee_basis_points": 0,
        "dev_seller_fee_basis_points": 0,
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": 0,
        "opensea_seller_fee_basis_points": 250,
        "buyer_fee_basis_points": 0,
        "seller_fee_basis_points": 250,
        "payout_address": null
      },
      "permalink": "https://testnets.opensea.io/assets/goerli/0xf37a02f497e21be9f4dd9a34c01568ac21578d1a/21",
      "collection": {
        "banner_image_url": "https://i.seadn.io/gcs/files/3566b4f16913cfb9bd746039f3ccfbe4.png?w=500&auto=format",
        "chat_url": null,
        "created_date": "2022-12-07T09:12:39.255914+00:00",
        "default_to_fiat": false,
        "description": "An assignment to test several types of images of NFTs.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {
          "card_display_style": "cover",
          "images": null
        },
        "external_url": "https://portto.com/",
        "featured": false,
        "featured_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "hidden": false,
        "safelist_request_status": "not_requested",
        "image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://i.seadn.io/gcs/files/a59c60b4d1de8145d9e1c05606d866e2.png?w=500&auto=format",
        "medium_username": null,
        "name": "BloctoAssignment",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "bloctoassignment",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null,
        "is_nsfw": false,
        "fees": {
          "seller_fees": {},
          "opensea_fees": {
            "0x0000a26b00c1f0df003000390027140000faa719": 250
          }
        },
        "is_rarity_enabled": false,
        "is_creator_fees_enforced": true
      },
      "decimals": null,
      "token_metadata": "https://ipfs.io/ipfs/QmZHvscH2h5dXFHHvVCedreFDBEfFDWAQxsMjJTBiiKuZi/21",
      "is_nsfw": false,
      "owner": null,
      "seaport_sell_orders": null,
      "creator": {
        "user": {
          "username": null
        },
        "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/23.png",
        "address": "0x85fd692d2a075908079261f5e351e7fe0267db02",
        "config": ""
      },
      "traits": [],
      "last_sale": null,
      "top_bid": null,
      "listing_date": null,
      "supports_wyvern": true,
      "rarity_data": null,
      "transfer_fee": null,
      "transfer_fee_payment_token": null,
      "token_id": "21"
    }
  ]
}
"""#

}
